# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "terminal-system-intel-layer"
BBFILE_PATTERN_terminal-system-intel-layer = "^${LAYERDIR}/"

LAYERDEPENDS_terminal-system-intel-layer = "terminal-system-layer"
LAYERSERIES_COMPAT_terminal-system-intel-layer = "scarthgap"
