#!/bin/bash -e

export RUNDIR="/var/run/device-inventory"
export CUSTOM_INVENTORY_DIR="${RUNDIR}/custom.d"
export PID_FILE="${RUNDIR}/device-inventory.pid"
export JSON_FILE="${RUNDIR}/device-inventory.json"
export TMP_FILE="${RUNDIR}/device-inventory.tmp"
export FIFO_FILE="${RUNDIR}/device-inventory.fifo"

export DC_INTDASH=/usr/bin/device-connector-intdash
export DC_INTDASH_CONF=/etc/dc_conf/zabbix_inventory.yml
export DC_PRINT_LOG_FILTER_CONF_TAG=device-inventory
export DC_FILE_SINK_CONF_PATH=${FIFO_FILE}

function help() {
    cat <<EOF
Usage: $(basename "${BASH_SOURCE[0]}") [OPTIONS] [INVENTORY_TYPE]

Options:
    -h, --help            Print this help and exit
    -d, --daemon          Run device-inventory daemon

INVENTORY_TYPE:
    --all                 Print all inventory (Default)
    --custom              Print custom inventory (JSON files stored in ${CUSTOM_INVENTORY_DIR})
    --df                  Print df
    --firmware            Print firmware
    --gps                 Print gps
    --intdash             Print intdash
    --ip                  Print ip
    --lsusb               Print lsusb
    --mmcli               Print mmcli
    --ping                Print ping
    --top                 Print top
    --vmstat              Print vmstat

EOF
}

function clean() {
    if "${DAEMON}"; then
        rm -rf "${RUNDIR}/"*
    fi
}
trap clean EXIT

function device_invetory_loop() {
    if [ -f "${PID_FILE}" ] && kill -0 $(cat "${PID_FILE}") 2>/dev/null; then
        echo "Error: device-inventory daemon is already running with pid: $(cat ${PID_FILE})."
        exit 1
    fi

    echo "start device-inventory daemon."
    local current_pid=$$
    mkdir -p "${RUNDIR}" "${CUSTOM_INVENTORY_DIR}"
    mkfifo "${FIFO_FILE}"
    echo $current_pid >"${PID_FILE}"

    DC_LOG=warn "${DC_INTDASH}" --config "${DC_INTDASH_CONF}" &
    local dc_pid=$!

    while [ -f "${PID_FILE}" ] && IFS= read -r line < "${FIFO_FILE}"; do
        if [ $current_pid -ne "$(cat "${PID_FILE}")" ]; then
            echo "Error: device-inventory daemon is restarted."
            kill $dc_pid
            exit 1
        fi

        echo "$line" > "$TMP_FILE"
        if ! jq . "$TMP_FILE" >/dev/null; then
            true > "${TMP_FILE}"
        fi
        mv -f "${TMP_FILE}" "${JSON_FILE}"
    done

    kill $dc_pid

    echo "Error: $PID_FILE is removed."
    exit 1
}

function wait_for_json_file() {
    local count_timeout=20
    local count=0

    while [ ! -f "${JSON_FILE}" ]; do
        if [ $count -eq $count_timeout ]; then
            echo "Error: ${JSON_FILE} is not found."
            exit 1
        fi
        sleep 1
        count=$((count + 1))
    done
}

function print_device_inventory() {
    if [ ! -f "${PID_FILE}" ]; then
        echo "Error: device-inventory daemon is not running."
        exit 1
    fi

    wait_for_json_file

    if "${PRINT_ALL}"; then
        filter="."
    else
        if [ ${#FILTERS[@]} -eq 0 ]; then
            help
            exit 1
        fi
        filter="{$(echo "${FILTERS[@]}" | tr ' ' ',')}"
    fi

    jq -c "$filter" "${JSON_FILE}"
}

DAEMON=false
PRINT_ALL=true
FILTERS=()

SHORT=h,d,i:
LONG=help,daemon,interval:,all,custom,df,firmware,gps,intdash,ip,lsusb,mmcli,ping,route,top,vmstat,who
OPTS=$(getopt -a --options $SHORT --longoptions $LONG -- "$@")

eval set -- "$OPTS"

while :; do
    case "$1" in
    -h | --help)
        help
        exit 0
        ;;
    -d | --daemon)
        DAEMON=true
        shift
        ;;
    -i | --interval)
        echo "Warning: interval option is ignored because deprecated." >&2
        shift 2
        ;;
    --all)
        PRINT_ALL=true
        shift
        ;;
    --route)
        echo "Warning: route option is ignored because deprecated." >&2
        shift
        ;;
    --who)
        echo "Warning: who option is ignored because deprecated." >&2
        shift
        ;;
    --)
        shift
        break
        ;;
    --*)
        FILTERS+=("${1#--}")
        PRINT_ALL=false
        shift
        ;;
    *)
        echo "Unexpected option: $1"
        ;;
    esac
done

if "${DAEMON}"; then
    device_invetory_loop
else
    print_device_inventory
fi
