image: $BASE_URI/$IMAGE_NAME_DEVICE_CONNECTOR:$IMAGE_TAG_DEVICE_CONNECTOR
restart: unless-stopped
privileged: true
runtime: nvidia
depends_on:
    intdash-edge-agent2:
        condition: service_healthy
volumes:
  - /var/run/core/intdash:/var/run/intdash
  - /tmp/argus_socket:/tmp/argus_socket # gstreamer fails to open the camera without the Argus daemon socket
  - /etc/enctune.conf:/etc/enctune.conf # To enable omxh264enc. see, https://aptpod-jp.atlassian.net/wiki/spaces/INTDASHCORE/pages/1074169039/Docker+T1
  - /dev:/dev
command:
    - --config
    - "/etc/dc_conf/gstreamer_jpeg.yml"
environment:
    DC_PROCESS_SRC_CONF_COMMAND: gst-launch-1.0 -q v4l2src device=${DC_DEVICE_PATH} ! queue ! videorate ! image/jpeg,width=${DC_WIDTH},height=${DC_HEIGHT},framerate=${DC_FPS}/1 ! queue ! fdsink fd=1
    DC_PRINT_LOG_FILTER_CONF_TAG: ${DC_TAG}
    DC_FILE_SINK_CONF_PATH: ${DC_UPSTREAM_FIFO_0}

substitution_variables:
    - key: DC_UPSTREAM_FIFO_0
      default: ''
      validation: '^/var/run/intdash/'
      display_strings_i18n:
        - locale: und
          name: FIFO Path
          description: intdash Edge Agent 2へデータを送信するためのFIFOのパス
    - key: DC_TAG
      default: 'mjpeg'
      display_strings_i18n:
        - locale: und
          name: Tag
          description: このデバイスコネクターのログメッセージに付与するタグ
    - key: DC_DEVICE_PATH
      default: '/dev/video0'
      path_glob:
        - /dev/v4l/by-id/usb-aptpod__Inc._EP1-VM01A*
        - /dev/video*
      display_strings_i18n:
        - locale: und
          name: Device Path
          description: カメラのデバイスパス
    - key: DC_WIDTH
      default: '640'
      options: ['640']
      display_strings_i18n:
        - locale: und
          name: Width
          description: 動画の幅
          unit: pixel
    - key: DC_HEIGHT
      default: '480'
      options: ['480']
      display_strings_i18n:
        - locale: und
          name: Height
          description: 動画の高さ
          unit: pixel
    - key: DC_FPS
      default: '15'
      options: ['1', '5', '10', '15', '30']
      display_strings_i18n:
        - locale: und
          name: Frame Rate
          description: フレームレート
          unit: fps
