image: $BASE_URI/$IMAGE_NAME_DEVICE_CONNECTOR:$IMAGE_TAG_DEVICE_CONNECTOR
restart: unless-stopped
privileged: true
depends_on:
    intdash-edge-agent2:
        condition: service_healthy
volumes:
  - /var/run/core/intdash:/var/run/intdash
  - /dev:/dev
  - /run/udev:/run/udev:ro # libcamerasrc needs udev https://github.com/raspberrypi/rpicam-apps/issues/270
command:
    - --config
    - "/etc/dc_conf/${DC_PIPELINE_CONFIG_FILE}"
environment:
    # gstreamer_h264.yml
    DC_PROCESS_SRC_CONF_COMMAND: ${DC_GST_PIPELINE}
    DC_H264_SPLIT_FILTER_CONF_DELAY_MS: 100
    DC_H264_SPLIT_FILTER_CONF_FORMAT: iscp_v2_compat
    # gstreamer_rtp.yml
    DC_GSTREAMER_SRC_PIPELINE: ${DC_GST_PIPELINE}
    DC_ISCP_V2_COMPAT_FILTER_NAME: ${DC_DATA_NAME}
    DC_ISCP_V2_COMPAT_FILTER_MEDIA_TYPE: ${DC_MEDIA_TYPE}
    DC_ISCP_V2_COMPAT_MODIFY_HEADER_OFFSET: -100
    # common
    DC_PRINT_LOG_FILTER_CONF_TAG: ${DC_TAG}
    DC_FILE_SINK_CONF_PATH: ${DC_UPSTREAM_FIFO_0}
    GST_DEBUG: 2

substitution_variables:
    - key: DC_UPSTREAM_FIFO_0
      default: ''
      validation: '^/var/run/intdash/'
      display_strings_i18n:
        - locale: und
          name: FIFO Path
          description: intdash Edge Agent 2へデータを送信するためのFIFOのパス
    - key: DC_TAG
      default: 'RPiCAM'
      display_strings_i18n:
        - locale: und
          name: Tag
          description: このデバイスコネクターのログメッセージに付与するタグ
    - key: DC_OUTPUT_DATA_TYPE
      default: 'H.264 RTP Packet (from YUY2)'
      presets:
        - name: H.264 Frame (from YUY2)
          variables:
            DC_PIPELINE_CONFIG_FILE: gstreamer_h264.yml
            # declare all input properties (framerate, colorimetry, interlace-mode) https://forums.raspberrypi.com/viewtopic.php?p=2081618&sid=693620c6e51d7a938b02745082f64e05#p2081618
            DC_GST_PIPELINE: gst-launch-1.0 -q libcamerasrc ! videorate drop-only=true ! video/x-raw,width=${DC_WIDTH},height=${DC_HEIGHT},framerate=${DC_FPS}/1,format=YUY2,colorimetry=bt709,interlace-mode=progressive ! videoflip video-direction=${DC_VIDEOFLIP} ! v4l2h264enc extra-controls='controls,video_bitrate=${DC_BITRATE},h264_i_frame_period=${DC_FPS}' ! 'video/x-h264,profile=main,level=(string)4,stream-format=byte-stream' ! queue ! h264parse ! queue ! fdsink fd=1
        - name: H.264 RTP Packet (from YUY2)
          variables:
            DC_PIPELINE_CONFIG_FILE: gstreamer_rtp.yml
            DC_GST_PIPELINE: libcamerasrc ! videorate drop-only=true ! video/x-raw,width=${DC_WIDTH},height=${DC_HEIGHT},framerate=${DC_FPS}/1,format=YUY2,colorimetry=bt709,interlace-mode=progressive ! videoflip video-direction=${DC_VIDEOFLIP} ! v4l2h264enc extra-controls='controls,video_bitrate=${DC_BITRATE},h264_i_frame_period=${DC_FPS}' ! 'video/x-h264,profile=main,level=(string)4,stream-format=byte-stream' ! queue ! h264parse config-interval=-1 ! rtph264pay ! queue ! appsink name=dcsink
            DC_MEDIA_TYPE: h264
      display_strings_i18n:
        - locale: und
          name: Output Data Type
          description: 出力データ型
    - key: DC_DATA_NAME
      conditional_options_script: "/etc/core/docker-compose/measurement/services/Camera/data_name.sh"
      cache_key_command: "echo -n Camera-data-name"
      display_strings_i18n:
        - locale: und
          name: Data Name
          description: データ名
    - key: DC_WIDTH
      default: '1280'
      options: ['1280', '1920']
      display_strings_i18n:
        - locale: und
          name: Width
          description: 動画の幅
          unit: pixel
    - key: DC_HEIGHT
      default: '720'
      options: ['720', '1080']
      display_strings_i18n:
        - locale: und
          name: Height
          description: 動画の高さ
          unit: pixel
    - key: DC_FPS
      default: '15'
      conditional_options_script: "/etc/core/docker-compose/measurement/services/Camera/fps_raspberry_pi_camera.sh"
      cache_key_command: "echo -n Camera-fps-raspberry-pi-camera"
      display_strings_i18n:
        - locale: und
          name: Frame Rate
          description: フレームレート
          unit: fps
    - key: DC_VIDEOFLIP
      default: 'identity'
      options: ['identity', '180', '90r', '90l', 'horiz', 'vert']
      display_strings_i18n:
        - locale: und
          name: Video Flip
          description: 回転・反転
    - key: DC_BITRATE
      default: '2000000'
      options: ['500000', '1000000', '2000000', '3000000', '5000000', '8000000']
      display_strings_i18n:
        - locale: und
          name: Bitrate
          description: ビットレート
          unit: bps
