image: $BASE_URI/$IMAGE_NAME_DEVICE_CONNECTOR:$IMAGE_TAG_DEVICE_CONNECTOR
restart: unless-stopped
depends_on:
    intdash-edge-agent2:
        condition: service_healthy
privileged: true
volumes:
  - /var/run/core/intdash:/var/run/intdash
  - /dev:/dev
command:
    - --config
    - "/etc/dc_conf/${DC_PIPELINE_CONFIG_FILE}"
environment:
    # gstreamer_pcm.yml
    DC_PCM_SPLIT_FILTER_CONF_PATH: ${DC_DEVICE_PATH}
    DC_PCM_SPLIT_FILTER_CONF_DELAY_MS: 0
    DC_PCM_SPLIT_FILTER_CONF_AUDIO_ELEMENT: ${DC_AUDIO_JACK_ELEMENT}
    DC_PCM_SPLIT_FILTER_CONF_AUDIO_IFACE: ${DC_AUDIO_JACK_IFACE}
    DC_PCM_SPLIT_FILTER_CONF_AUDIO_FORMAT: ${DC_AUDIO_FORMAT}
    DC_PCM_SPLIT_FILTER_CONF_AUDIO_RATE: ${DC_AUDIO_RATE}
    DC_PCM_SPLIT_FILTER_CONF_AUDIO_CHANNELS: 1
    DC_PCM_SPLIT_FILTER_CONF_AUDIO_SYNC_PERIOD_S: ""
    # gstreamer_rtp_opus.yml
    DC_RTP_OPUS_AUDIO_DEVICE_PATH: ${DC_DEVICE_PATH}
    DC_ISCP_V2_COMPAT_MODIFY_HEADER_OFFSET_MS: -25
    DC_RTP_OPUS_AUDIO_ELEMENT: ${DC_AUDIO_JACK_ELEMENT}
    DC_RTP_OPUS_AUDIO_IFACE: ${DC_AUDIO_JACK_IFACE}
    DC_RTP_OPUS_AUDIO_BITRATE: ${DC_BITRATE}
    DC_RTP_OPUS_AUDIO_BITRATE_TYPE: ${DC_BITRATE_TYPE}
    DC_RTP_OPUS_AUDIO_FRAME_SIZE: 20
    DC_RTP_OPUS_AUDIO_CHANNELS: 1
    DC_ISCP_V2_COMPAT_FILTER_NAME: ${DC_DATA_NAME}
    # common
    DC_UTILS_ALSA_MIXER_ARGS: ${DC_MIXER_ARGS}
    DC_PRINT_LOG_FILTER_CONF_TAG: ${DC_TAG}
    DC_FILE_SINK_CONF_PATH: ${DC_UPSTREAM_FIFO_0}
    GST_DEBUG: 2

substitution_variables:
    - key: DC_UPSTREAM_FIFO_0
      default: ''
      validation: '^/var/run/intdash/'
      display_strings_i18n:
        - locale: und
          name: FIFO Path
          description: intdash Edge Agent 2へデータを送信するためのFIFOのパス
    - key: DC_TAG
      default: 'audio'
      display_strings_i18n:
        - locale: und
          name: Tag
          description: このデバイスコネクターのログメッセージに付与するタグ
    - key: DC_OUTPUT_DATA_TYPE
      default: 'PCM'
      presets:
        - name: 'PCM'
          variables:
            DC_PIPELINE_CONFIG_FILE: gstreamer_pcm.yml
        - name: 'Opus RTP Packet'
          variables:
            DC_PIPELINE_CONFIG_FILE: gstreamer_rtp_opus.yml
      display_strings_i18n:
        - locale: und
          name: Output Data Type
          description: 出力データ型
    - key: DC_DATA_NAME
      default: ''
      conditional_options_script: "/etc/core/docker-compose/measurement/services/Audio/data_name.sh"
      cache_key_command: "echo -n Audio-data-name"
      display_strings_i18n:
        - locale: und
          name: Data Name
          description: データ名
    - key: DC_DEVICE_PATH
      default: ''
      options_script: "/etc/core/docker-compose/measurement/services/Audio/device_path.sh"
      cache_key_command: "echo -n Audio-device-path-$(ls -al /dev/snd/by-*/* | md5sum -z)"
      display_strings_i18n:
        - locale: und
          name: Device Path
          description: 音声入力デバイスのデバイスパス
    - key: DC_AUDIO_JACK_ELEMENT
      default: ''
      conditional_options_script: "/etc/core/docker-compose/measurement/services/Audio/audio_jack_element.sh"
      cache_key_command: "echo -n Audio-audio-jack-element-$(ls -al /dev/snd/by-*/* | md5sum -z)"
      display_strings_i18n:
        - locale: und
          name: Audio Jack Element
          description: オーディオジャックの挿抜検知に使用するALSAエレメント名（挿抜検知をしない場合は設定不要）
    - key: DC_AUDIO_JACK_IFACE
      default: ''
      conditional_validation_script: "/etc/core/docker-compose/measurement/services/Audio/audio_jack_iface.sh"
      cache_key_command: "echo -n Audio-audio-jack-iface-$(ls -al /dev/snd/by-*/* | md5sum -z)"
      display_strings_i18n:
        - locale: und
          name: Audio Jack Interface
          description: オーディオジャックの挿抜検知に使用するALSAインターフェイス名（挿抜検知をしない場合は設定不要）
    - key: DC_AUDIO_FORMAT
      default: ''
      conditional_options_script: "/etc/core/docker-compose/measurement/services/Audio/audio_format.sh"
      cache_key_command: "echo -n Audio-audio-format"
      display_strings_i18n:
        - locale: und
          name: Format
          description: 音声データの形式 ※PCM選択時のみ有効
    - key: DC_AUDIO_RATE
      default: ''
      conditional_options_script: "/etc/core/docker-compose/measurement/services/Audio/audio_rate.sh"
      cache_key_command: "echo -n Audio-audio-rate"
      display_strings_i18n:
        - locale: und
          name: Sampling Rate
          description: 音声データのサンプリング周波数
          unit: Hz
    - key: DC_BITRATE
      default: ''
      conditional_options_script: "/etc/core/docker-compose/measurement/services/Audio/audio_bitrate.sh"
      cache_key_command: "echo -n Audio-audio-bitrate"
      display_strings_i18n:
        - locale: und
          name: Bitrate
          description: 音声データのビットレート ※Opus選択時のみ有効
          unit: bps
    - key: DC_BITRATE_TYPE
      default: ''
      conditional_options_script: "/etc/core/docker-compose/measurement/services/Audio/audio_bitrate_type.sh"
      cache_key_command: "echo -n Audio-audio-bitrate-type"
      display_strings_i18n:
        - locale: und
          name: Bitrate Type
          description: 音声データのビットレートの種類（cbr:固定ビットレート、vbr:可変ビットレート、constrained-vbr:制約付き可変ビットレート） ※Opus選択時のみ有効
    - key: DC_MIXER_ARGS
      default: ''
      conditional_validation_script: "/etc/core/docker-compose/measurement/services/Audio/mixer_args.sh"
      cache_key_command: "echo -n Audio-mixer-args-$(ls -al /dev/snd/by-*/* | md5sum -z)"
      display_strings_i18n:
        - locale: und
          name: Volume
          description: 音声データの音量（"項目名=0-100%" の形式で指定。","で区切って複数の設定が可能。例："y Mic=100%,y Mic Boost=32%"）
