image: $BASE_URI/$IMAGE_NAME_DEVICE_CONNECTOR:$IMAGE_TAG_DEVICE_CONNECTOR
restart: unless-stopped
depends_on:
    intdash-edge-agent2:
        condition: service_healthy
privileged: true
volumes:
  - /var/run/core/intdash:/var/run/intdash
  - /dev:/dev
command:
    - --config
    - "/etc/dc_conf/gstreamer_pcm.yml"
environment:
    DC_PCM_SPLIT_FILTER_CONF_PATH: ${DC_DEVICE_PATH}
    DC_PCM_SPLIT_FILTER_CONF_DELAY_MS: 0
    DC_PCM_SPLIT_FILTER_CONF_AUDIO_ELEMENT: ${DC_AUDIO_JACK_ELEMENT}
    DC_PCM_SPLIT_FILTER_CONF_AUDIO_IFACE: ${DC_AUDIO_JACK_IFACE}
    DC_PCM_SPLIT_FILTER_CONF_AUDIO_FORMAT: ${DC_AUDIO_FORMAT}
    DC_PCM_SPLIT_FILTER_CONF_AUDIO_RATE: 48000
    DC_PCM_SPLIT_FILTER_CONF_AUDIO_CHANNELS: 1
    DC_UTILS_ALSA_MIXER_ARGS: ${DC_MIXER_ARGS}
    DC_PCM_SPLIT_FILTER_CONF_AUDIO_SYNC_PERIOD_S: ""
    DC_PRINT_LOG_FILTER_CONF_TAG: ${DC_TAG}
    DC_FILE_SINK_CONF_PATH: ${DC_UPSTREAM_FIFO_0}

substitution_variables:
    - key: DC_UPSTREAM_FIFO_0
      default: ''
      validation: '^/var/run/intdash/'
      display_strings_i18n:
        - locale: jpn
          name: FIFO Path
          description: intdash Edge Agent 2へデータを送信するためのFIFOのパス
    - key: DC_TAG
      default: 'audio'
      display_strings_i18n:
        - locale: jpn
          name: Tag
          description: このデバイスコネクターのログを表示するときに使用するタグ
    - key: DC_DEVICE_PATH
      default: ''
      options_script: "/etc/core/docker-compose/measurement/services/Audio/device_path.sh"
      display_strings_i18n:
        - locale: jpn
          name: Device Path
          description: デバイスパスを指定することで、使用する音声入力デバイスを選択
    - key: DC_AUDIO_JACK_ELEMENT
      default: ''
      conditional_options_script: "/etc/core/docker-compose/measurement/services/Audio/audio_jack_element.sh"
      display_strings_i18n:
        - locale: jpn
          name: Audio Jack Element
          description: ジャックの挿抜検知に用いるエレメント名
    - key: DC_AUDIO_JACK_IFACE
      default: ''
      conditional_validation_script: "/etc/core/docker-compose/measurement/services/Audio/audio_jack_iface.sh"
      display_strings_i18n:
        - locale: jpn
          name: Audio Jack Interface
          description: ジャックの挿抜検知に用いるインターフェイス名、Audio Elementに有効な値が指定されている場合以外は使用されない
    - key: DC_AUDIO_FORMAT
      default: 'S16LE'
      options: ['S16LE', 'S32LE', 'F32LE']
      display_strings_i18n:
        - locale: jpn
          name: Format
          description: 音声データの形式
    - key: DC_MIXER_ARGS
      default: ''
      conditional_validation_script: "/etc/core/docker-compose/measurement/services/Audio/mixer_args.sh"
      display_strings_i18n:
        - locale: jpn
          name: Volume
          description: 音声データの音量設定。`項目名=0-100%` で指定する。`,`で区切って複数設定も可能（例：`y Mic=100%,y Mic Boost=32%`）。
