image: $BASE_URI/$IMAGE_NAME_DEVICE_CONNECTOR:$IMAGE_TAG_DEVICE_CONNECTOR
restart: unless-stopped
privileged: true
depends_on:
    intdash-edge-agent2:
        condition: service_healthy
volumes:
  - intdash-lock:/var/lock/intdash
  - /var/run/core/intdash:/var/run/intdash
  - /dev:/dev
command:
    - --config
    - "/etc/dc_conf/apt_cantrx_upstream.yml"
environment:
    DC_APT_CANTRX_SRC_CONF_PATH: ${DC_DEVICE_PATH}
    DC_APT_CANTRX_SRC_CONF_LISTENONLY: ${DC_LISTENONLY}
    DC_APT_CANTRX_SRC_CONF_BAUDRATE: ${DC_BAUDRATE}
    DC_APT_CANTRX_SRC_CONF_TIMESTAMP_MODE: ${DC_TIMESTAMP_MODE}
    DC_PRINT_LOG_FILTER_CONF_TAG: ${DC_TAG}
    DC_FILE_SINK_CONF_PATH: ${DC_UPSTREAM_FIFO_0}

substitution_variables:
    - key: DC_UPSTREAM_FIFO_0
      default: ''
      validation: '^/var/run/intdash/'
      display_strings_i18n:
        - locale: jpn
          name: FIFO Path
          description: intdash Edge Agent 2へデータを送信するためのFIFOのパス
    - key: DC_TAG
      default: 'can(upstream)'
      display_strings_i18n:
        - locale: jpn
          name: Tag
          description: このデバイスコネクターのログを表示するときに使用するタグ
    - key: DC_DEVICE_PATH
      default: '/dev/aptUSB0'
      path_glob:
        - /dev/apt-usb/by-id/usb-aptpod__Inc._EP1-CH*
        - /dev/apt-usb/by-id/usb-aptpod__Inc._AP-CT2A_*
        - /dev/apt-usb/by-id/usb-STMicroelectronics_CAN-USB_transceiver*
        - /dev/aptUSB*
      display_strings_i18n:
        - locale: jpn
          name: Device Path
          description: CAN-USB Interfaceのデバイスパス
    - key: DC_TIMESTAMP_MODE
      default: 'device'
      options: ['device', 'host']
      display_strings_i18n:
        - locale: jpn
          name: Timestamp Mode
          description: 受信したデータに対して、タイムスタンプをどのように付与するか
    - key: DC_LISTENONLY
      default: '1'
      options: ['0', '1']
      display_strings_i18n:
        - locale: jpn
          name: Listen Only
          description: CAN-USB InterfaceからCANバスにACKを送信するかどうか（0:ACKあり、1:ACKなし）
    - key: DC_BAUDRATE
      default: '500'
      options: ['125', '250', '500', '1000']
      display_strings_i18n:
        - locale: jpn
          name: Baud Rate
          description: CAN通信のボーレート
          unit: Kbps
