image: $BASE_URI/$IMAGE_NAME_DEVICE_CONNECTOR:$IMAGE_TAG_DEVICE_CONNECTOR
restart: unless-stopped
privileged: true
depends_on:
    intdash-edge-agent2:
        condition: service_healthy
network_mode: host
volumes:
  - intdash-lock:/var/lock/intdash
  - /var/run/core/intdash:/var/run/intdash
  - /var/lib/core/intdash:/var/lib/intdash
  - /dev:/dev
command:
    - --config
    - "/etc/dc_conf/ep_canfd_upstream.yml"
environment:
    DC_EP_CANFD_SRC_CONF_PATH: ${DC_DEVICE_PATH}
    DC_EP_CANFD_SRC_CONF_STORE_ENABLED: ${DC_STORE_ENABLED}
    DC_EP_CANFD_SRC_CONF_STORE_MAX_DURATION_SEC: ${DC_STORE_MAX_DURATION}
    DC_EP_CANFD_SRC_CONF_DATA_NAME_PREFIX: ${DC_DATA_NAME_PREFIX}
    DC_EP_CANFD_SRC_CONF_LISTENONLY: ${DC_LISTENONLY}
    DC_EP_CANFD_SRC_CONF_FD: ${DC_FD}
    DC_EP_CANFD_SRC_CONF_FD_NON_ISO: ${DC_FD_NON_ISO}
    DC_EP_CANFD_SRC_CONF_BITRATE: ${DC_BITRATE}
    DC_EP_CANFD_SRC_CONF_SAMPLE_POINT: ${DC_SAMPLE_POINT}
    DC_EP_CANFD_SRC_CONF_DBITRATE: ${DC_DBITRATE}
    DC_EP_CANFD_SRC_CONF_DSAMPLE_POINT: ${DC_DSAMPLE_POINT}
    DC_EP_CANFD_SRC_CONF_TIMESTAMP_MODE: ${DC_TIMESTAMP_MODE}
    DC_EP_CANFD_SRC_CONF_ID_MAP: /var/lib/intdash/dc-ep_canfd-id_map
    DC_EP_CANFD_SRC_STORE_COMPLETE_MAP: /var/lib/intdash/dc-ep_canfd-store_complete_map
    DC_EP_CANFD_SRC_CONF_AGENT_DAEMON_URL: http://127.0.0.1:50051
    DC_PRINT_LOG_FILTER_CONF_TAG: ${DC_TAG}
    DC_FILE_SINK_CONF_PATH: ${DC_UPSTREAM_FIFO_0}

substitution_variables:
    - key: DC_UPSTREAM_FIFO_0
      default: ''
      validation: '^/var/run/intdash/'
      display_strings_i18n:
        - locale: und
          name: FIFO Path
          description: intdash Edge Agent 2へデータを送信するためのFIFOのパス
    - key: DC_TAG
      default: 'canfd(upstream)'
      display_strings_i18n:
        - locale: und
          name: Tag
          description: このデバイスコネクターのログメッセージに付与するタグ
    - key: DC_DEVICE_PATH
      default: '/dev/aptUSB0'
      path_glob:
        - /dev/apt-usb/by-id/usb-aptpod__Inc._EP1-CF02A_*
        - /dev/aptUSB*
      display_strings_i18n:
        - locale: und
          name: Device Path
          description: CAN FD USB Interfaceのデバイスパス
    - key: DC_STORE_ENABLED
      default: 'false'
      options: ['true', 'false']
      display_strings_i18n:
        - locale: und
          name: Store Enabled
          description: データ保持機能の有効化（true:USB接続確立前のデータを取得する、false:USB接続確立前のデータを取得しない）
    - key: DC_STORE_MAX_DURATION
      default: '300'
      validation: '^(0|[1-9][0-9]*)$'
      display_strings_i18n:
        - locale: und
          name: Store Max Duration
          description: 1回の計測で内蔵ストレージに保持するデータの最大時間（0:無制限、データ保持機能有効時のみ有効）
          unit: sec
    - key: DC_DATA_NAME_PREFIX
      default: ''
      display_strings_i18n:
        - locale: und
          name: Data Name Prefix
          description: データ名に付与するプレフィックス（データ保持機能有効時のみ指定）※この設定でプレフィックスを指定する場合、アップストリームIPC設定のデータ名に付与するプレフィックスは必ず空文字にしてください。
    - key: DC_FD
      default: 'true'
      options: ['true', 'false']
      display_strings_i18n:
        - locale: und
          name: CAN FD
          description: CAN FD有効化
    - key: DC_FD_NON_ISO
      default: 'false'
      options: ['true', 'false']
      display_strings_i18n:
        - locale: und
          name: non-ISO CAN FD
          description: CAN FD使用時のnon-ISOモード（true:有効、false:無効）
    - key: DC_LISTENONLY
      default: 'true'
      options: ['true', 'false']
      display_strings_i18n:
        - locale: und
          name: Listen Only
          description: Listen Onlyモード（false:CAN FD USB InterfaceからCANバスへのACK送信あり、true:ACK送信なし）
    - key: DC_BITRATE
      default: '500000'
      options: ['125000', '250000', '500000', '1000000']
      display_strings_i18n:
        - locale: und
          name: Bitrate
          description: CAN通信のビットレート
          unit: bps
    - key: DC_SAMPLE_POINT
      default: ''
      validation: '^(|0.[0-9][0-9][0-9])$'
      display_strings_i18n:
        - locale: und
          name: Sample Point
          description: CAN通信のサンプルポイント（設定が空文字の場合は自動計算される。自動計算時のサンプルポイント：500Kbps以下=0.875、500Kbps超〜800Kbps以下=0.800、800Kbps超=0.750）
    - key: DC_DBITRATE
      default: '5000000'
      validation: '^(|[1-9][0-9]{0,5}|[1-7][0-9]{6}|8000000)$'
      display_strings_i18n:
        - locale: und
          name: Bitrate for Data Phase
          description: CANデータ通信のビットレート
          unit: bps
    - key: DC_DSAMPLE_POINT
      default: ''
      validation: '^(|0.[0-9][0-9][0-9])$'
      display_strings_i18n:
        - locale: und
          name: Sample Point for Data Phase
          description: CANデータ通信のサンプルポイント（設定が空文字の場合は自動計算される。自動計算時のサンプルポイント：500Kbps以下=0.875、500Kbps超〜800Kbps以下=0.800、800Kbps超=0.750）
    - key: DC_TIMESTAMP_MODE
      default: 'device'
      options: ['device', 'host']
      display_strings_i18n:
        - locale: und
          name: Timestamp Mode
          description: データのタイムスタンプに使用するクロック（device:CAN FD USB Interfaceのクロック、host:Terminal Systemコンピューターのクロック）※データ保持機能を使用してUSB接続確立前のデータも取得する場合はdeviceを指定
