image: $BASE_URI/$IMAGE_NAME_DEVICE_CONNECTOR:$IMAGE_TAG_DEVICE_CONNECTOR
restart: unless-stopped
depends_on:
    intdash-edge-agent2:
        condition: service_healthy
volumes:
  - /var/run/core/intdash:/var/run/intdash
  - /var/run/device-inventory:/var/run/device-inventory
command:
    - --config
    - "/etc/dc_conf/repeat_process_json.yml"
environment:
    DC_REPEAT_PROCESS_SRC_CONF_COMMAND:
      if [ $(cat /var/run/device-inventory/interval) -ne ${DC_SEND_INTERVAL} ]; then
          echo ${DC_SEND_INTERVAL} > /var/run/device-inventory/interval;
      fi;
      cat /var/run/device-inventory/device-inventory.json;
    DC_REPEAT_PROCESS_SRC_CONF_INTERVAL_MS: ${DC_SEND_INTERVAL}000
    DC_ISCP_V2_COMPAT_FILTER_CONF_CONVERT_RULE_STRING_NAME: device_inventory
    DC_PRINT_LOG_FILTER_CONF_TAG: ${DC_TAG}
    DC_FILE_SINK_CONF_PATH: ${DC_UPSTREAM_FIFO_0}
substitution_variables:
    - key: DC_UPSTREAM_FIFO_0
      default: ''
      validation: '^/var/run/intdash/'
      display_strings_i18n:
        - locale: jpn
          name: FIFO Path
          description: intdash Edge Agent 2へデータを送信するためのFIFOのパス
    - key: DC_TAG
      default: 'device-inventory'
      display_strings_i18n:
        - locale: jpn
          name: Tag
          description: このデバイスコネクターのログを表示するときに使用するタグ
    - key: DC_SEND_INTERVAL
      default: 10
      validation: '^[1-9][0-9]*$'
      display_strings_i18n:
        - locale: jpn
          name: Send Interval
          description: デバイスインベントリの送信間隔
          unit: sec
