image: $BASE_URI/$IMAGE_NAME_DEVICE_CONNECTOR:$IMAGE_TAG_DEVICE_CONNECTOR
restart: unless-stopped
privileged: true
depends_on:
    intdash-edge-agent2:
        condition: service_healthy
volumes:
  - /var/run/core/intdash:/var/run/intdash
  - /dev:/dev
command:
    - --config
    - "/etc/dc_conf/jpeg.yml"
environment:
    DC_V4L2_SRC_CONF_PATH: ${DC_DEVICE_PATH}
    DC_V4L2_SRC_WIDTH: ${DC_WIDTH}
    DC_V4L2_SRC_HEIGHT: ${DC_HEIGHT}
    DC_V4L2_SRC_FPS: ${DC_FPS}
    DC_PRINT_LOG_FILTER_CONF_TAG: ${DC_TAG}
    DC_FILE_SINK_CONF_PATH: ${DC_UPSTREAM_FIFO_0}

substitution_variables:
    - key: DC_UPSTREAM_FIFO_0
      default: ''
      validation: '^/var/run/intdash/'
      display_strings_i18n:
        - locale: jpn
          name: FIFO Path
          description: intdash Edge Agent 2へデータを送信するためのFIFOのパス
    - key: DC_TAG
      default: 'mjpeg(v4l2-src)'
      display_strings_i18n:
        - locale: jpn
          name: Tag
          description: このデバイスコネクターのログを表示するときに使用するタグ
    - key: DC_DEVICE_PATH
      default: '/dev/video0'
      path_glob:
        - /dev/v4l/by-id/usb-aptpod__Inc._EP1-VM01A*
        - /dev/video*
      display_strings_i18n:
        - locale: jpn
          name: Device Path
          description: デバイスパスを指定することで、使用するカメラを選択
    - key: DC_WIDTH
      default: '640'
      options: ['640']
      display_strings_i18n:
        - locale: jpn
          name: Width
          description: 取得する動画の解像度の幅
          unit: pixel
    - key: DC_HEIGHT
      default: '480'
      options: ['480']
      display_strings_i18n:
        - locale: jpn
          name: Height
          description: 取得する動画の解像度の高さ
          unit: pixel
    - key: DC_FPS
      default: '15'
      options: ['1', '5', '10', '15', '30']
      display_strings_i18n:
        - locale: jpn
          name: Frame Rate
          description: フレームレートを選択
          unit: fps
